### ISSUE TITLE
npm ERR! peer dep missing: mongoose@, required by mongoose-type-email

### ISSUE THREAD

**Issue by sobolevn** [konsumer/mongoose-type-email#3]
Found this little error. I guess you have to update this line: https://github.com/konsumer/mongoose-type-email/blob/master/package.json#L32

> [23:13:53] sobolev :: MacBook-Pro-Nikita  ➜  Documents/Frontends/razgrebaem ‹master*› » npm list mongoose 
> razgrebaem@1.0.0 /Users/sobolev/Documents/Frontends/razgrebaem
> └── UNMET PEER DEPENDENCY mongoose@4.6.4
> 
> npm ERR! peer dep missing: mongoose@, required by mongoose-type-email@1.0.2
> npm ERR! peer dep missing: mongoose@, required by mongoose-type-url@1.0.2
> npm ERR! code 1

**Comment by konsumer** [comment]
In your project, run `npm i -S mongoose`. It's a peer-dep, which means your project needs to use it already. This project isn't at all useful without mongoose (it's a field-type for mongoose schema.) Peer-deps used to be automatically installed, but they aren't now, so it isn't automatically added to your project.

**Comment by sobolevn** [comment]
I already have it my `package.json`, that's not the issue. https://github.com/wemake-services/razgrebaem.ru/blob/master/package.json#L27

It happens because your version specification is invalid: https://github.com/konsumer/mongoose-type-email/blob/master/package.json#L32 

Here's the specification: https://docs.npmjs.com/misc/semver

p.s. Closing issues like that is little bit harsh.

**Comment by konsumer** [comment]
It's not invalid. An empty string is the same as `*`. Please see [this](https://docs.npmjs.com/files/package.json#dependencies). Just having the dep in your package.json isn't enough, it has to actually be installed in your project (hence the `npm install` advice.) 

PS: I didn't intend to be harsh. I thought I had resolved your issue. Did you try it?

**Comment by sobolevn** [comment]
Nope, that didn't help. I still can live with it, but it is just does not feel right.

Maybe that issue is caused by using `yarn`? https://github.com/wemake-services/razgrebaem.ru/blob/master/yarn.lock#L4046

**Comment by konsumer** [comment]
Yeh, I don't use yarn. If you have a string to put in there to work around this yarn bug, I'd be happy to put it in the package.json, but it might make sense to file an issue with yarn.

**Comment by konsumer** [comment]
To clarify, [here it's peer-dependency illustrated](https://asciinema.org/a/756zm11mnj0qe0a6sv6nbf6hu).
