### ISSUE TITLE
When used together with required:true it raises the wrong error message

### ISSUE THREAD

**Issue by AnotherCodeArtist** [konsumer/mongoose-type-email#32]
Since 1.0.11 validation of an invalid email brings up a `required` error instead of `invalid email address` when used together with `required: true`.

**Comment by konsumer** [comment]
Hmm, I don't see any changes in 1.0.11 `validateEmail()` that should cause the order of validation operations to be different.

I think other mongoose field-types generally fail on `required` first, then on more specific validation. If email didn't do this before, I think it was a bug or oversight, but I suspect an upstream update to mongoose changed the default behavior for everyone.

I'm going to close, but feel free to comment if there are other things related to this.
