### ISSUE TITLE
 yarn add  mongoose-type-email  error. 

### ISSUE THREAD

**Issue by Flutter-Stack** [konsumer/mongoose-type-email#33]
yarn add  mongoose-type-email
yarn add v1.17.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/mongoose-type-email: getaddrinfo EAI_AGAIN registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by konsumer** [comment]
Maybe a temporary problem with yarn? It looks ok now, to me:
https://registry.yarnpkg.com/mongoose-type-email
