### ISSUE TITLE
Update cryptiles to @hapi/cryptiles

### ISSUE THREAD

**Issue by alejandroalfonsoyero** [konsumer/mongoose-type-email#36]
This is to avoid this
npm WARN deprecated cryptiles@4.1.3: This module has moved and is now available at @hapi/cryptiles. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by deniz-frick** [comment]
Even worse!
cryptiles is not used in the code at all!
Its dead code and should be removed from package.json

**Comment by konsumer** [comment]
Yeh, I think I added it as an explicit dep to fix an outdated dep in something else. I don't really have the bandwidth to update and test right now, but if you want to update the deps, and Install & test (rm node_modules, fresh install, etc) I'm happy to accept a PR (and publish update)

**Comment by konsumer** [comment]
Ok, I removed it, updated deps, got a clean audit, and published as `1.0.13`. Tests seem to run fine, but let me know if there are other issues.
