### ISSUE TITLE
When field's required is a function, allowBlank doesn't work.

### ISSUE THREAD

**Issue by fyodoriv** [konsumer/mongoose-type-email#5]
Hey, nice plugin!
However, I am having an issue with `allowBlank` when field's `required` is set to a function.

To reproduce have this schema:

```js
require('mongoose-type-email')
const { Schema } = mongoose

const userSchema = new Schema({
  email: {
    allowBlank: true,
    default: '',
    required: function() {
      return false // returning false here for the sake of the display
    },
    type: mongoose.SchemaTypes.Email,
  }
})
```
Most likely this is happening because on this line https://github.com/konsumer/mongoose-type-email/blob/master/index.js#L6 it doesn't check if the `required` is a functon and that it doesn't return false.

**Comment by konsumer** [comment]
I didn't know setting `required` to a function was supported! Looking at it...

**Comment by fyodoriv** [comment]
@konsumer thanks, it worked! :]

**Comment by konsumer** [comment]
😁
