### ISSUE TITLE
allowBlank with null value?

### ISSUE THREAD

**Issue by fyodoriv** [konsumer/mongoose-type-email#6]
Hey, is it possible to add support for `allowBlank` so that not only `''`, but `null` also counts as blank? The use case is that I have
```js
  email: {
    allowBlank: true,
    default: '', // want it to default to null
    type: mongoose.SchemaTypes.Email,
    unique: true,
  },
```

and the problem is that 2 emails with `''` as values don't pass the unique validation. Having those as `null`s will make the uniqueness validation pass.

Seems that the fix would be checking `val` not only for `''`, but for `null` on this line https://github.com/konsumer/mongoose-type-email/blob/master/index.js#L7

**Comment by konsumer** [comment]
Hi, I'd be happy to accept a PR.

**Comment by fyodoriv** [comment]
@konsumer please review it, would be glad to respond to your comments =]

**Comment by konsumer** [comment]
Thanks again, looks great!
